# Generated by Django 5.1.4 on 2025-01-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='application_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
